---
title: 'Chapter 4: Linear Models'
output: html_document
---

```{r log}

log_big <- replicate(1000,
                     log(prod(1 + runif(12, 0, 0.5))))

hist(log_big)

plot(density(log_big))

```


```{r}
curve(dnorm(x,178,20), from = 100, to = 250)
```

```{r}
curve(dunif(x,0,50), from = 10, to = 60)
```

Sampling to get an idea of what our heights might look like:

```{r}
sample_mu <- rnorm(1e4, 178, 20)

sample_sigma <- runif(1e4, 0, 50)

prior_h <- rnorm(1e4, sample_mu, sample_sigma)

rethinking::dens(prior_h)
```

Playing around with the parameters of the priors to see how this effects the prior probability density of heights.


Code chunk 4.14

setup - get the data

```{r}
library(rethinking)
data(Howell1)

d <- Howell1

d2 <- d[d$age >= 18, ]
```


```{r}
# create the grid of values of mu
mu.list <- seq(from = 140,
               to = 160,
               length.out = 200)

# create the grid of values of sigma
sigma.list <- seq(from = 4,
                  to = 9,
                  length.out = 200)

# get every combination of mu and sigma
post <- expand.grid(mu = mu.list,
                    sigma = sigma.list)

# now, for all the values of mu and sigma, create a normal distribution,
# 
post$LL <- sapply(1:nrow(post),
                  function(i){
                    sum(dnorm(x = d2$height,
                              mean = post$mu[i],
                              sd = post$sigma[i],
                              log = TRUE))
                  })

post$prod <- post$LL + 
  dnorm(x = post$mu, 
        mean = 178, 
        sd = 20, 
        log = TRUE) + 
  dunif(x = post$sigma,
        min = 0,
        max = 50,
        log = TRUE)

post$prob <- exp(post$prod - max(post$prod))
```

plot the contours with

```{r}
contour_xyz(post$mu,
             post$sigma,
             post$prob)
```

Looks like there's some large spaces that have suuuuper low density?

now for an image plot

```{r}
image_xyz(post$mu,
          post$sigma,
          post$prob)
```

# 4.3.4 Sampling from the posterior.

4.17

```{r}

sample.rows <- sample(1:nrow(post),
                      size = 1e4,
                      replace = TRUE,
                      prob = post$prob)

sample.mu <- post$mu[sample.rows]

sample.sigma <- post$sigma[sample.rows]

```

4.18

```{r}
plot(sample.mu,
     sample.sigma,
     cex = 0.7,
     pch = 16,
     col = col.alpha(rangi2, 0.5))
```

4.19

```{r}
dens(sample.mu)
dens(sample.sigma)
```

4.20

```{r}
HPDI(sample.mu)
HPDI(sample.sigma)
```

